apiVersion: v3
kind: PipelineConfig
metadata:
  title: "{{pipelinename}} - Medallion Pipeline Template"
  name: {{pipelinename}}
spec:
  # Global Variables - defaults for all profiles
  variables:
    - name: OPEN_METADATA_REST_API
      value: "http://openmetadata.cortex.svc.cluster.local:8585/api" # cluster internal API
    - name: DBT_EXECUTION_STRING
      value: build
  profiles:
    # Local Profile - for local usage. It uses a JDBC connection in the local catalog and sets an arbitrary value
    # for the OpenMetadata token because it is stubbed during tests as the service is not available
    - name: local
      variables:
        - name: PROJECT
          value: test-project
        - name: INPUT_CONNECTION_NAME
          value: local-csv
        - name: DATA_SOURCE_NAME
          value: test-datasource
        - name: PROFILE_NAME
          value: test-profileschema
        - name: OPEN_METADATA_TOKEN
          value: 'xxxxx'
    # Default profile - for use in a Sensa cluster (use at your own risk).
    - name: default
      variables:
        - name: OPEN_METADATA_TOKEN
          value: '<REPLACE_ME>'
        - name: INPUT_CONNECTION_NAME
          value: '<REPLACE_ME>'
  blocks:
    - name: bronze
      title: Bronze
      class: BronzeBlock
      package: bronze
      executor: pyspark
      type: streaming
      inputs:
        - name: bronze_input
          sensa:
            connection:
              project: ${PROJECT}
              name: ${INPUT_CONNECTION_NAME}
      outputs:
        - name: to_bronze
          sensa:
            model:
              project: ${PROJECT}
              name: bronze
    - name: dbt_silver
      # TODO: why do this run both Silver & GOLD - seems a little counterintuitive
      title: DBT Silver And Gold
      class: SilverBlock
      package: silver
      executor: pyspark
      type: dbt
      dbt:
        projectDir: dbt/{{pipelinename}}
        profileDir: dbt
        runCommand: ${DBT_EXECUTION_STRING}
      inputs:
        - name: from_bronze
          sensa:
            model:
              project: ${PROJECT}
              name: bronze
      outputs:
        - name: to_data_source
          sensa:
            dataSource:
              project: ${PROJECT}
              name: ${DATA_SOURCE_NAME}
        - name: to_profile_schema
          sensa:
            profile:
              project: ${PROJECT}
              name: ${PROFILE_NAME}
    - name: gold
      title: Gold
      class: GoldBlock
      package: gold
      executor: pyspark
      type: streaming
      inputs:
        - name: from_profile_schema
          sensa:
            profile:
              project: ${PROJECT}
              name: ${PROFILE_NAME}
      outputs:
        - name: to_gold_checkpoint
          sensa:
            model:
              project: ${PROJECT}
              name: gold
