apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "local-file"
spec:
  title: Local File
  description: Local CSV File for the Medallion Pipeline
  connectionType: file
  contentType: csv
  allowRead: true
  allowWrite: false
  params:
  - name: uri
    value: pipelines/{{pipelinename}}/seeds/data.csv
  - name: csv/header
    value: true
---
apiVersion: cognitivescale.io/v1
kind: Connection
metadata:
  name: "local-file-json"
spec:
  title: Local JSON File
  description: Local JSON File for the Medallion Pipeline
  tags: []
  connectionType: file
  contentType: json
  allowRead: true
  allowWrite: false
  params:
    - name: json/multiline
      value: "true"
    - name: json/style
      value: lines
    - name: uri
      value: pipelines/{{pipelinename}}/seeds/data.json
